FROM alpine:3.15

LABEL maintainer="NGINX Docker Maintainers <docker-maint@nginx.com>"

ARG HTML_FILE
ENV HTML_FILE=$HTML_FILE

RUN apk add --no-cache aws-cli 

RUN apk add --no-cache nginx tzdata     

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

RUN mkdir /etc/nginx/html
RUN chmod -R 755 /etc/nginx/html/
RUN mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf_original
COPY nginx.conf /etc/nginx/nginx.conf
COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

EXPOSE 80



