FROM openjdk:8
ENV RUN_ARGS="--server.port=80 --server.ssl.enabled=false"
RUN apt-get update && apt-get install -y --no-install-recommends python3-pip awscli
COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh
#ENTRYPOINT ["./entrypoint.sh"]

